# Generated by Django 5.0.1 on 2024-06-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
