# Generated by Django 5.0.1 on 2024-06-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
