# Generated by Django 5.0.1 on 2024-06-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_empleado_celular_alter_empleado_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="foto_final",
        ),
        migrations.RemoveField(
            model_name="report",
            name="foto_inicial",
        ),
        migrations.AddField(
            model_name="report",
            name="foto_final_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="foto_inicial_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
