# Generated by Django 5.0.1 on 2024-07-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_empleado_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="ubicacion",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
