# Generated by Django 5.0.1 on 2024-09-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_empleado_ubicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(default="Pendiente", max_length=50),
        ),
    ]
