# Generated by Django 5.0.1 on 2024-09-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0010_remove_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="prioridad",
            field=models.CharField(
                choices=[("Alta", "Alta"), ("Media", "Media"), ("Baja", "Baja")],
                default="Media",
                max_length=5,
            ),
        ),
    ]
