# Generated by Django 5.0.1 on 2025-08-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.ubicacion'),
        ),
    ]
