# Generated by Django 5.0.1 on 2025-08-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='status',
            field=models.CharField(default='ready', max_length=20),
        ),
    ]
